# logger options
snapshot_save_iter: 20     # How often do you want to save trained models

#
input_dim: 3                                # number of image channels [1/3]
gen_length: 4096
test_size: 1000

# optimization options
max_epoch: 1000              # maximum number of training iterations
batch_size: 256               # batch size
weight_decay: 0.0001          # weight decay
beta1: 0.5                    # Adam parameter
beta2: 0.999                  # Adam parameter
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
lr: 0.0001                    # initial learning rate
gamma: 0.5                    # how much to decay learning rate
